### ISSUE TITLE
Against the Scarlet Triad: Red Pyramid First Floor 

### ISSUE THREAD

**Issue by MothMariner** [Kalnix/age-of-ashes-map-remakes-by-kalnix#1]
Just walling up the Red Pyramid First Floor and you've got the passage that should go under the left-hand royal chambers going directly through them instead. Admittedly it's not visible in the book's image of the map, but it is visible in the interactive maps version (and described so in the book).

**Comment by Kalnix** [comment]
Fixed this as part of the module release
